# Nome da Aplicação
spring.application.name=apex-clear

# Configurações de Conexão com o PostgreSQL 13
spring.datasource.url=jdbc:postgresql://localhost:5433/apex_clear_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Força o Hibernate a falar a língua do PostgreSQL 13
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Inicialização
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Timeout do Lock
jakarta.persistence.lock.timeout=5000